### ISSUE TITLE
Subset of 1001 list

### ISSUE THREAD

**Issue by SimonsPaul** [phax/validation#296]
Dear,

Currently, the validation artefacts only allow codes that are listed in the subset of the 1001 list that is cited in Annex A of the syntax binding documents. This is a mistake. Annex A states: "Many codes in this list do not designate Invoices or Credit Notes. For the codes that do in the following table it is shown how the code must be interpreted by the receiving system. This is an initial subset. Newly added codes may be added to this subset". Meant is 'added by user communities'. It is even stated that "additions also need agreement regarding the interpretation [by the user communities]". General validation artefacts therefore should only test if a code is part of the 1001 list. User communities may add additional validation to test compliance to their subset.

On behalf of TC434 mgmt,
Paul Simons
Convenor WG1

**Comment by phax** [comment]
E.g. the german XRechnung extension uses new codes like `875` etc. So from there point of view that would be a benefit. Does that mean - we don't need the explicit rule anymore?

**Comment by svanteschubert** [comment]
The problem seems valid from my perspective, too!
Can we please have some more information why not solving it? 
Thanks in advance!

**Comment by oriol** [comment]
The problem is that this issue was raised yesterday, and the new artefacts were published two days ago.

We need to improve the process of communicating the resolutions from the CEN TC434 in order to get them duly included.

**Comment by midran** [comment]
Testing for the full 1001 and thus indicating that according to EN 16931 any document type code listed now and in the future in that code list is a valid implementation of the eInvoicing standard. This would means that turning it into an order or catalogue with document type codes 105 and 9 is a valid implementation of the EN 16931 and thus would constitute a compliance to the eInvoicing directive. The EN 16931 could even be declared as being 853 - Veterinary certificate and so forth.

This obviously makes no sense. Suggesting this only because of a short term issue with new codes can not be justified.

This is a procedural problem, not a technical one.

**Comment by dwillekens** [comment]
I am only following existing CEF procedures. The request was filed in may. 2021 (according to these CEF procedures) after consulting CEN TC434 WG1 (where request was accepted). I do fully understand OpenPeppol is based on the subset defined by CEF (so subset CEF should be adapted first). The problem here is that existing procedures have been broken when stopping CEF and DEP not taking over existing procedures in place. I wonder how this situation can be resolved on short terms? Any suggestions?

**Comment by SimonsPaul** [comment]
CEF and CEN TC434 are taking care of this issue to get it solved. Communication will follow shortly. The issue can be closed.
