### ISSUE TITLE
ISO 4217 VEF/VES

### ISSUE THREAD

**Issue by ri4a** [phax/validation#373]
ISO 4217 changed VEF to VES in 2018, but this change has not been implemented.

See

- https://en.wikipedia.org/wiki/ISO_4217
- https://www.six-group.com/dam/download/financial-information/data-center/iso-currrency/amendments/dl_currency_iso_amendment_168.pdf

**Comment by midran** [comment]
Code VEF has already been removed, Code VES is in the list of code, Code VED is being added in the Nov24 release. These are all for Venezuela and are due to changes in the denomication of the Bolivar currency. Currently there are two codes for the Bolivar in different denominations. VES and VED.

https://www.currency-iso.org/dam/downloads/dl_currency_iso_amendment_170.pdf
https://www.currency-iso.org/dam/downloads/dl_currency_iso_amendment_168.pdf

**Comment by midran** [comment]
#390
